name: Docker Image CI

on:
  push:
    branches:
      - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: |
        IMAGE=gllera/ws
        echo ${{ secrets.TOKEN_DOCKER }} | docker login --username gllera --password-stdin
        docker build . --tag $IMAGE
        docker push $IMAGE
